# SPDX-FileCopyrightText: Elias Mueller
#
# SPDX-License-Identifier: MIT

name: Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  verify_formatting:
    runs-on: ubuntu-latest
    name: Lint & Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Run pre-commit hooks
        uses: j178/prek-action@v2
      - name: Verify REUSE compliance
        uses: fsfe/reuse-action@v6

  test:
    runs-on: ubuntu-latest
    name: Tests
    container: fedora:44
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Install system dependencies
        run: |
          dnf install -y dnf5-plugins just uv dbus-daemon
          dnf copr enable -y avengemedia/dms
          dnf install -y quickshell
      - name: Run system tests
        run: |
          export XDG_RUNTIME_DIR="$(mktemp -d)"
          just test
